import { useState } from 'react'
import { dlModels, classicalMethods, type DLModel } from '../data/projectData'

type SortKey = 'name' | 'testAcc' | 'f1' | 'params' | 'speed'

const SPEED_ORDER: Record<DLModel['speed'], number> = { 'very fast': 4, fast: 3, medium: 2, slow: 1 }

function parseParams(p: string): number {
  const s = p.replace('~', '')
  if (s.endsWith('M')) return parseFloat(s) * 1e6
  if (s.endsWith('K')) return parseFloat(s) * 1e3
  return parseFloat(s)
}

const TYPE_LABELS: Record<DLModel['type'], string> = {
  transformer: 'Transformer',
  transfer: 'Transfer learning',
  custom: 'Custom CNN',
  'classic-dl': 'From scratch',
}

export default function ModelComparison() {
  const [sortKey, setSortKey] = useState<SortKey>('testAcc')
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc')
  const base = import.meta.env.BASE_URL

  function handleSort(key: SortKey) {
    if (key === sortKey) setSortDir(d => (d === 'desc' ? 'asc' : 'desc'))
    else { setSortKey(key); setSortDir('desc') }
  }

  const sorted = [...dlModels].sort((a, b) => {
    let diff = 0
    if (sortKey === 'testAcc') diff = a.testAcc - b.testAcc
    else if (sortKey === 'f1') diff = a.f1 - b.f1
    else if (sortKey === 'params') diff = parseParams(a.params) - parseParams(b.params)
    else if (sortKey === 'speed') diff = SPEED_ORDER[a.speed] - SPEED_ORDER[b.speed]
    else diff = a.name.localeCompare(b.name)
    return sortDir === 'desc' ? -diff : diff
  })

  function Th({ label, k }: { label: string; k: SortKey }) {
    const active = sortKey === k
    return (
      <th onClick={() => handleSort(k)} title={`Sort by ${label}`}>
        {label}{active ? (sortDir === 'desc' ? ' ↓' : ' ↑') : ''}
      </th>
    )
  }

  return (
    <section id="comparison">
      <hr className="sec" />
      <h2 className="text-lg font-bold mb-4">3. Results</h2>

      <h3 className="text-sm font-bold mb-2">3.1 Deep Learning Models (GTSRB)</h3>
      <p className="text-xs text-gray-500 italic mb-3">
        Table 1. Test performance on GTSRB (43 classes, 5 epochs, batch size 128, Adam optimizer).
        All models except LeNet and MY_NET use ImageNet pretrained weights.
        Click column headers to sort. Hover a row for architecture notes.
      </p>

      <div className="overflow-x-auto mb-2">
        <table className="tbl">
          <thead>
            <tr>
              <Th label="Model"    k="name"    />
              <th>Architecture</th>
              <Th label="Test Acc" k="testAcc" />
              <Th label="F1"       k="f1"      />
              <Th label="Params"   k="params"  />
              <Th label="Speed"    k="speed"   />
              <th>Best use</th>
            </tr>
          </thead>
          <tbody>
            {sorted.map(m => (
              <tr key={m.name} title={m.note}>
                <td><strong>{m.name}</strong></td>
                <td className="text-gray-600">{TYPE_LABELS[m.type]}</td>
                <td className="tabular-nums">{(m.testAcc * 100).toFixed(2)}%</td>
                <td className="tabular-nums text-gray-600">{(m.f1 * 100).toFixed(2)}%</td>
                <td className="tabular-nums text-gray-600">{m.params}</td>
                <td className="text-gray-600">{m.speed}</td>
                <td className="text-gray-600">{m.suitability}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="text-xs text-gray-500 mb-6">
        Real metrics from <code>bonus/analysis/model_comparison_summary.json</code>, a 5-epoch
        comparison run. README values such as ViT ~98.7% and AlexNet ~98.5% summarize approximate
        best/longer-run results and are not mixed into this table.
      </p>

      {/* Model comparison figure */}
      <figure className="mb-8">
        <img
          src={`${base}images/model_comparison.png`}
          alt="Model comparison: accuracy, F1, and training curves for all 7 architectures"
          className="w-full border border-gray-300"
        />
        <figcaption className="text-xs text-gray-500 italic mt-1 text-center">
          Figure 2. Left: test accuracy. Center: macro F1-score. Right: training loss curves (5 epochs).
          Generated by <code>bonus/analysis/compare_all_models.py</code>.
        </figcaption>
      </figure>

      <div className="mb-8 border border-gray-300 p-4">
        <h3 className="text-sm font-bold mb-2">What this comparison suggests</h3>
        <ul className="text-sm list-disc pl-5 space-y-1">
          <li>Classical CV is useful as an interpretable baseline.</li>
          <li>Transfer learning gives the strongest practical accuracy-efficiency tradeoff.</li>
          <li>ViT performs best in this experiment, but its deployment cost matters.</li>
        </ul>
      </div>

      <h3 className="text-sm font-bold mb-2">3.2 Classical Methods (Dataset 1)</h3>
      <p className="text-xs text-gray-500 italic mb-2">
        Table 2. Classical method summary. Exact metrics were not saved; run the referenced notebooks to reproduce.
      </p>
      <table className="tbl mb-2">
        <thead>
          <tr>
            <th>Method</th>
            <th>Test Accuracy</th>
            <th>Dataset</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          {classicalMethods.map(m => (
            <tr key={m.name}>
              <td><strong>{m.name}</strong></td>
              <td className="tabular-nums">{m.testAcc} *</td>
              <td className="text-gray-600">{m.dataset}</td>
              <td className="text-gray-600">{m.note}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p className="text-xs text-gray-500 mb-6">* Placeholder / approximate — exact results not saved.</p>

      {/* Dataset analysis figure */}
      <figure>
        <img
          src={`${base}images/data_analysis.png`}
          alt="Dataset analysis: class distribution, ROI sizes, and class imbalance"
          className="w-full border border-gray-300"
        />
        <figcaption className="text-xs text-gray-500 italic mt-1 text-center">
          Figure 3. GTSRB dataset analysis. Top row: class distribution (train vs. test), ROI size scatter,
          ROI area histogram. Bottom row: imbalance ratio, samples per class.
          Generated by <code>bonus/analysis/data_analysis.py</code>.
        </figcaption>
      </figure>
    </section>
  )
}
