import { useState } from 'react'
import { dlModels, classicalMethods, type DLModel } from '../data/projectData'

type SortKey = 'name' | 'testAcc' | 'f1' | 'params' | 'speed'

const TYPE_BADGE: Record<DLModel['type'], string> = {
  transformer: 'bg-purple-500/10 text-purple-300 border border-purple-500/20',
  transfer:    'bg-blue-500/10 text-blue-300 border border-blue-500/20',
  custom:      'bg-emerald-500/10 text-emerald-300 border border-emerald-500/20',
  'classic-dl': 'bg-slate-500/10 text-slate-300 border border-slate-500/20',
}

const SPEED_ORDER: Record<DLModel['speed'], number> = { 'very fast': 4, fast: 3, medium: 2, slow: 1 }

function parseParams(p: string): number {
  const cleaned = p.replace('~', '')
  if (cleaned.endsWith('M')) return parseFloat(cleaned) * 1e6
  if (cleaned.endsWith('K')) return parseFloat(cleaned) * 1e3
  return parseFloat(cleaned)
}

function AccBar({ value }: { value: number }) {
  const pct = +(value * 100).toFixed(1)
  const color = value >= 0.97 ? 'bg-purple-500' : value >= 0.95 ? 'bg-blue-500' : value >= 0.90 ? 'bg-emerald-500' : 'bg-amber-500'
  return (
    <div className="flex items-center gap-2">
      <div className="w-20 bg-slate-700 rounded-full h-1.5">
        <div className={`${color} h-1.5 rounded-full`} style={{ width: `${pct}%` }} />
      </div>
      <span className="text-xs text-slate-200 tabular-nums">{pct}%</span>
    </div>
  )
}

function SortHeader({ label, sortKey, active, dir, onSort }: {
  label: string; sortKey: SortKey; active: SortKey; dir: 'asc' | 'desc'; onSort: (k: SortKey) => void
}) {
  const isActive = active === sortKey
  return (
    <th
      onClick={() => onSort(sortKey)}
      className="px-3 py-2 text-left text-xs font-medium text-slate-400 cursor-pointer hover:text-white select-none whitespace-nowrap"
    >
      {label}
      <span className="ml-1 text-slate-600">{isActive ? (dir === 'desc' ? '↓' : '↑') : '↕'}</span>
    </th>
  )
}

export default function ModelComparison() {
  const [sortKey, setSortKey] = useState<SortKey>('testAcc')
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc')

  function handleSort(key: SortKey) {
    if (key === sortKey) setSortDir(d => d === 'desc' ? 'asc' : 'desc')
    else { setSortKey(key); setSortDir('desc') }
  }

  const sorted = [...dlModels].sort((a, b) => {
    let diff = 0
    if (sortKey === 'testAcc') diff = a.testAcc - b.testAcc
    else if (sortKey === 'f1')  diff = a.f1 - b.f1
    else if (sortKey === 'params') diff = parseParams(a.params) - parseParams(b.params)
    else if (sortKey === 'speed')  diff = SPEED_ORDER[a.speed] - SPEED_ORDER[b.speed]
    else diff = a.name.localeCompare(b.name)
    return sortDir === 'desc' ? -diff : diff
  })

  const base = import.meta.env.BASE_URL

  return (
    <section id="comparison" className="py-20 px-4 border-t border-slate-800">
      <div className="max-w-5xl mx-auto">
        <div className="flex items-start justify-between flex-wrap gap-4 mb-2">
          <div>
            <h2 className="text-2xl md:text-3xl font-bold text-white">Model Comparison</h2>
            <p className="text-slate-500 text-sm mt-1">
              Deep learning results on GTSRB (43 classes, 5 epochs, batch 128)
            </p>
          </div>
          <span className="text-xs px-2 py-1 rounded-full bg-emerald-500/10 text-emerald-300 border border-emerald-500/20 self-start mt-1">
            Real metrics
          </span>
        </div>

        {/* Charts from training */}
        <div className="mb-10 rounded-xl overflow-hidden border border-slate-700">
          <img
            src={`${base}images/model_comparison.png`}
            alt="Model comparison chart: accuracy, F1-score, and training curves"
            className="w-full"
          />
          <div className="px-4 py-2 bg-slate-800 text-xs text-slate-500">
            Generated by <code>bonus/analysis/compare_all_models.py</code>
          </div>
        </div>

        {/* Interactive table */}
        <div className="mb-3 flex items-center gap-2">
          <span className="text-sm text-slate-300 font-medium">Interactive table</span>
          <span className="text-xs text-slate-500">— click column headers to sort</span>
        </div>

        <div className="overflow-x-auto rounded-xl border border-slate-700">
          <table className="w-full text-sm">
            <thead className="bg-slate-800">
              <tr>
                <SortHeader label="Model"     sortKey="name"    active={sortKey} dir={sortDir} onSort={handleSort} />
                <th className="px-3 py-2 text-left text-xs font-medium text-slate-400 whitespace-nowrap">Type</th>
                <SortHeader label="Test Acc"  sortKey="testAcc" active={sortKey} dir={sortDir} onSort={handleSort} />
                <SortHeader label="F1"        sortKey="f1"      active={sortKey} dir={sortDir} onSort={handleSort} />
                <SortHeader label="Params"    sortKey="params"  active={sortKey} dir={sortDir} onSort={handleSort} />
                <SortHeader label="Speed"     sortKey="speed"   active={sortKey} dir={sortDir} onSort={handleSort} />
                <th className="px-3 py-2 text-left text-xs font-medium text-slate-400">Best for</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-700/50">
              {sorted.map(m => (
                <tr key={m.name} className="hover:bg-slate-800/40 transition-colors" title={m.note}>
                  <td className="px-3 py-3 font-medium text-slate-200 whitespace-nowrap">{m.name}</td>
                  <td className="px-3 py-3">
                    <span className={`text-xs px-2 py-0.5 rounded-full ${TYPE_BADGE[m.type]}`}>
                      {m.type === 'classic-dl' ? 'from scratch' : m.type}
                    </span>
                  </td>
                  <td className="px-3 py-3"><AccBar value={m.testAcc} /></td>
                  <td className="px-3 py-3 text-slate-300 tabular-nums">{(m.f1 * 100).toFixed(1)}%</td>
                  <td className="px-3 py-3 text-slate-300 tabular-nums">{m.params}</td>
                  <td className="px-3 py-3">
                    <span className={`text-xs ${m.speed === 'very fast' ? 'text-emerald-400' : m.speed === 'fast' ? 'text-blue-400' : 'text-amber-400'}`}>
                      {m.speed}
                    </span>
                  </td>
                  <td className="px-3 py-3 text-slate-400 text-xs max-w-[140px]">{m.suitability}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="mt-2 text-xs text-slate-600">Hover a row to see architecture notes.</p>

        {/* Classical methods */}
        <div className="mt-10">
          <div className="flex items-center gap-2 mb-3">
            <h3 className="text-base font-semibold text-slate-200">Classical Methods</h3>
            <span className="text-xs px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-300 border border-amber-500/20">
              Placeholder / approximate
            </span>
          </div>
          <div className="grid md:grid-cols-2 gap-4">
            {classicalMethods.map(m => (
              <div key={m.name} className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4">
                <div className="flex items-start justify-between gap-3 mb-2">
                  <span className="text-sm font-medium text-slate-200">{m.name}</span>
                  <span className="text-xs text-amber-300 bg-amber-500/10 px-2 py-0.5 rounded-full shrink-0">
                    {m.testAcc}
                  </span>
                </div>
                <p className="text-xs text-slate-400 mb-1">{m.note}</p>
                <p className="text-xs text-slate-500">{m.dataset}</p>
              </div>
            ))}
          </div>
          <p className="mt-3 text-xs text-slate-600">
            Exact classical metrics were not saved. Run <code className="text-slate-500">expert/task.ipynb</code> to generate results.
          </p>
        </div>

        {/* Dataset analysis chart */}
        <div className="mt-10 rounded-xl overflow-hidden border border-slate-700">
          <img
            src={`${base}images/data_analysis.png`}
            alt="Dataset analysis: class distribution, ROI sizes, imbalance"
            className="w-full"
          />
          <div className="px-4 py-2 bg-slate-800 text-xs text-slate-500">
            Generated by <code>bonus/analysis/data_analysis.py</code>
          </div>
        </div>
      </div>
    </section>
  )
}
